export const jobMock = {
  location: {
    notes: 'sdfghjkl',
    city: 'Минск',
    type: 'street_address',
    details: 'Parking lot',
    lat: 53.9076675,
    state: 'Минская область',
    address: 'Проспект Победителей 7а, Минск, Беларусь',
    long: 27.5496635,
  },
  service: {
    description: 'Tire & wheels, repair & replacement',
    flatRate: 200,
    disclaimerChecked: true,
    answers: {
      cdsdcscss: 'sdfg',
      cscsssds: 'dfghjkl',
      questionNr1: 'dfsgs',
    },
    iconId: 14,
    issue: '3456789',
    hourly: true,
    commonParts: [],
    id: 'bZCJVob5paszrUxGcNeY',
    questions: [{ text: 'Tire size?' }, { text: 'Drive, steer, or trailer?' }],
    minHours: 2,
    name: 'Tire repair / replacement',
    disclaimer:
      'Tires cannot be returned once purchased. If the incorrect tire size was specified you will be billed for the tire.',
  },
  vehicle: {
    mileage: '22222',
    model: '222',
    vin: '222222',
    usdot: '22222',
    make: '2222',
    unit: '2222',
    year: '2222',
  },
  isPendingReview: true,
  jobNumber: 287,
  id: 'VlVwYOPlIcfl22pssLnH',
  updatedby: 'a.fursa@andersenlab.com',
  status: 5,
  lastupdate: { seconds: 1645782386, nanoseconds: 302000000 },
  dispatcher: {
    noTextMessages: false,
    firstName: '2222',
    phoneNumber: '(100) 000-0000',
    lastName: '22222',
  },
  driver: { noTextMessages: false },
  parts: [],
  createdate: { seconds: 1645782341, nanoseconds: 828000000 },
  serviceArea: {
    state: 'Novogrudok',
    lastupdate: { seconds: 1639725513, nanoseconds: 68000000 },
    callout: 10,
    active: true,
    googleReviewLinkUrl: ' ',
    epicenter: { lat: '53.597488', long: '25.825220' },
    createdby: 'a.fursa@andersenlab.com',
    id: 'CTrySji8prehsq3AFkca',
    afterHour: 10,
    createdate: { seconds: 1639725493, nanoseconds: 150000000 },
    name: 'Novogrudok',
    fuel: 25,
    base: 10,
    updatedby: 'a.fursa@andersenlab.com',
  },
  timezone: 'Europe/Minsk',
  createdby: 'a.fursa@andersenlab.com',
  requests: [],
};
